apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-deployment
  labels:
    app: backend-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-k8s
  template:
    metadata:
      name: backend-k8s-pod
      labels:
        app: backend-k8s
    spec:
      containers:
      - name: backend-k8s-container
        image: backend-k8s
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-service
  labels:
    app: backend-k8s
spec:
  type: ClusterIP 
  selector:
    app: backend-k8s
  ports:
    - protocol: TCP
      port: 4000 
      targetPort: 3000 
