# Create secrets
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: admin
  password: "12345678"
---
# Creacion de un pod
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    env: # Determinamos que son variables de entorno
      - name: USERTEST # Nombre de la variable de entorno
        valueFrom:
          secretKeyRef: # Vamos a utilizar secrets en los envs
            name: secret1 # Nombre del secret que deseas utilizar
            key: username # LLave de acceso a la data del secrets
      - name: PASSWORDTEST
        valueFrom:
          secretKeyRef:
            name: secret1
            key: password
    volumeMounts: # Especificamos que vamos a utilizar u volumen
    - name: test # Nombre del volumen que deseas utilizar
      mountPath: "/opt" # Path en donde se creara el volumen
      readOnly: true # Que esto es de solo lectura
  volumes:
  - name: test # Nombre de nuestro volumen
    secret: # Damos a entender que vamos a utilizar secretos
      secretName: secret1 # Nombre del secreto que deseas utilizar
      items:
      - key: username # LLave del secreto
        path: user.txt # El archivo en donde se creara el secreto