# Secrets con data
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque # Es un tipo de secreto por defecto
data: # Cuando utilizamos data todo toca ponerlo en base64
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
# Estan en string data
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque # Es un tipo de secreto por defecto
stringData: # Cuando utilizamos string data podemos utilizarlo sin codificarlo en base64
  username: root
  password: root
---
# Pormedio de las variables de entorno
# Para poder utilizar varibales de entorno privadas tenemos que crear un script en donde reemplace los llamados $NAME y ponga las variables de entorno.
# Recomiendan (envsubst) envsubst < file_name.yaml > temp.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: $USER
  password: $PASSWORD